const inquire = require('inquirer');
const fs = require('fs');
const util = require('util');

const writeFileAsync = util.promisify(fs.writeFile);
// prompt from inquirer

const readmePrompt = () =>
  inquire.prompt([
    {
      type: 'input',
      name: 'title',
      message: 'What is the title of your project?',
    },
    {
      type: 'input',
      name: 'description',
      message: 'Please type a brief description of your project.',
    },
    {
      type: 'input',
      name: 'installation',
      message: 'Input installation instructions you want displayed.',
    },
    {
      type: 'input',
      name: 'usage',
      message: 'Input your usage instructions.',
    },
    {
      type:'list',
      name:'license',
      message: 'Which license would you like displayed?',
      choices: ['MIT', 'Apache', 'Boost', 'Eclipse', 'WTFPL']
    },
    {
      type: 'input',
      name: 'contribution',
      message: 'Input your contribution instructions',
    },
    {
      type: 'input',
      name: 'tests',
      message: 'Input testing information',
    },
    {
      type: 'input',
      name: 'username',
      message: 'What is your GitHub username?'  
    },
    {
      type: 'input',
      name: 'email',
      message: 'What is your email address?'  
    }
  ]);

// Object storing the various license badges and info

const licenseInfo = {
    MIT : {badge : '![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)',
           info : `Copyright <YEAR> <COPYRIGHT HOLDER>

           Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
           
           The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
           
           THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
           (https://opensource.org/licenses/MIT)`},
    Apache : {badge : '![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)',
              info : `Copyright [yyyy] [name of copyright owner]

              Licensed under the Apache License, Version 2.0 (the "License");
              you may not use this file except in compliance with the License.
              You may obtain a copy of the License at
           
                http://www.apache.org/licenses/LICENSE-2.0
           
              Unless required by applicable law or agreed to in writing, software
              distributed under the License is distributed on an "AS IS" BASIS,
              WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
              See the License for the specific language governing permissions and
              limitations under the License.`},
    Boost : {badge : '![License](https://img.shields.io/badge/License-Boost%201.0-lightblue.svg)',
             info : `Boost Software License - Version 1.0 - August 17th, 2003

             Permission is hereby granted, free of charge, to any person or organization
             obtaining a copy of the software and accompanying documentation covered by
             this license (the "Software") to use, reproduce, display, distribute,
             execute, and transmit the Software, and to prepare derivative works of the
             Software, and to permit third-parties to whom the Software is furnished to
             do so, all subject to the following:
             
             The copyright notices in the Software and this entire statement, including
             the above license grant, this restriction and the following disclaimer,
             must be included in all copies of the Software, in whole or in part, and
             all derivative works of the Software, unless such copies or derivative
             works are solely in the form of machine-executable object code generated by
             a source language processor.
             
             THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
             IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
             FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
             SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
             FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
             ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
             DEALINGS IN THE SOFTWARE.`},
    Eclipse : {badge : '![License](https://img.shields.io/badge/License-EPL%201.0-red.svg)',
               info : `THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE PUBLIC LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM CONSTITUTES RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT.
               (https://opensource.org/licenses/EPL-1.0)`},
    WTFPL : {badge : '![License: WTFPL](https://img.shields.io/badge/License-WTFPL-brightgreen.svg)',
             info : `DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
             Version 2, December 2004 

Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 

Everyone is permitted to copy and distribute verbatim or modified 
copies of this license document, and changing it is allowed as long 
as the name is changed. 

     DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

0. You just DO WHAT THE FUCK YOU WANT TO.
(http://www.wtfpl.net/about/)`}
}

// template generator function


const templateGen = (input) =>  
`># ${input.title}
${licenseInfo[input.license].badge}
---

#### ${input.description}
---

>## Table of Contents
---
- [Installation](###Installation)
- [Usage](###Usage)
- [License](###License)
- [Contribution](###Contribution)
- [Tests](###Tests)
- [Questions](###Questions)
    
>### Installation
    
${input.installation}

---
    
>### Usage
    
${input.usage}

---

>### License
    
${licenseInfo[input.license].info}

---

>### Contribution
    
${input.contribution}

---

>### Tests

${input.tests}

---
    
>### Questions
    
If you have a questions please connect with me on Github [${input.username}](https://github.com/${input.username})
or send me an email at <${input.email}>

---
    
#### Thanks for Viewing!`;


readmePrompt()
    .then(input => writeFileAsync('newREADME.md', templateGen(input)))
    .catch(err => console.error(err));
